# Generated by Django 5.1.4 on 2026-09-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_code', models.CharField(max_length=40, verbose_name='灯号一')),
                ('second_code', models.CharField(max_length=40, verbose_name='灯号二')),
                ('first_verdict', models.CharField(max_length=20, verbose_name='判词一')),
                ('second_verdict', models.CharField(max_length=20, verbose_name='判词二')),
                ('first_measured_cd', models.FloatField(verbose_name='实测一光强')),
                ('second_measured_cd', models.FloatField(verbose_name='实测二光强')),
                ('first_required_cd', models.FloatField(verbose_name='实测一要求光强')),
                ('second_required_cd', models.FloatField(verbose_name='实测二要求光强')),
                ('first_bearing_error_deg', models.FloatField(verbose_name='实测一方位偏差')),
                ('second_bearing_error_deg', models.FloatField(verbose_name='实测二方位偏差')),
                ('brightness_diff', models.FloatField(verbose_name='亮度差')),
                ('bearing_diff', models.FloatField(verbose_name='偏角差')),
                ('created_by', models.CharField(max_length=64, verbose_name='留存人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets_first', to='inspection.inspection', verbose_name='实测一')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets_second', to='inspection.inspection', verbose_name='实测二')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
